--- vscode-neovim settings here
local vscode = require("vscode")

vim.opt.timeoutlen = 300

vim.keymap.set({ "n" }, "<Leader>h", function()
  vscode.action("workbench.action.navigateLeft")
end)
vim.keymap.set({ "n" }, "<Leader>l", function()
  vscode.action("workbench.action.navigateRight")
end)
vim.keymap.set({ "n" }, "<Leader>k", function()
  vscode.action("workbench.action.navigateUp")
end)
vim.keymap.set({ "n" }, "<Leader>j", function()
  vscode.action("workbench.action.navigateDown")
end)
vim.keymap.set({ "n" }, "<Leader><Leader><Leader>", function()
  vscode.action("whichkey.show")
end)
vim.keymap.set({ "n" }, "<Leader><Leader>", function()
  vscode.action("workbench.action.quickOpen")
end)
vim.keymap.set({ "n" }, "<Leader>,", function()
  vscode.action("workbench.action.showAllEditors")
end)
vim.keymap.set({ "n" }, "<Leader>-", function()
  vscode.action("workbench.action.splitEditorDown")
end)
vim.keymap.set({ "n" }, "<Leader>|", function()
  vscode.action("workbench.action.splitEditor")
end)
